on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [fedora-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: build with cmake
      run: |
        cmake -B build
        cmake --build build
    - uses: cpina/github-action-push-to-another-repository@main
    - name: Pushes to another repository
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'output'
        destination-github-username: 'EpitechPromo2025'
        destination-repository-name: 'B-DOP-400-TLS-4-1-bsmymarvin-iona.dommel-prioux'
        user-email: iona.dommel-prioux@epitech.eu
        target-branch: main