on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [fedora-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: build with cmake
      run: |
        cmake -B build
        cmake --build build